server:
  port: 10010
spring:
  application:
    name: junhi-zuul


zuul:
  routes:
    service-provider: /service-provider/**  # \u8DEF\u7531\u540D\u79F0\uFF0C\u53EF\u4EE5\u968F\u4FBF\u5199\uFF0C\u4E60\u60EF\u4E0A\u670D\u52A1\u6C11
  prefix: /api  # zuul\u7F51\u5173\u7684\u524D\u7F00\uFF0C\u53EF\u52A0\u53EF\u4E0D\u52A0\uFF0C\u63A8\u8350\u52A0\u4E0A

#      path: /service-provider/**
#      url: http://localhost:8083
#      serviceId: service-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka  # \u5C06zuul\u6CE8\u518C\u5230eureka
